version: '3.7'
services:
    web:
        build: ./src
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./src/:/usr/projects/swipe/src
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:13.3
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=top1Dron
            - POSTGRES_DB=swipedb
        ports:
            - 5431:5432