version: '3.7'
services:
    web:
        restart: always
        build: 
            context: ./src
            dockerfile: Dockerfile.prod
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
        volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media
            - .:/src
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        restart: always
        image: postgres:13.3
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
        ports:
            - 5431:5432
    nginx:
        restart: always
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media
        ports:
            - 1337:80
        depends_on:
            - web
        
volumes:
    static_volume:
    media_volume:
