# Generated by Django 3.2.8 on 2021-10-20 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcementrequest',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='an_request', to='swipe.announcement'),
        ),
        migrations.AlterField(
            model_name='housenews',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_news', to='swipe.house'),
        ),
    ]
