# Generated by Django 3.2.8 on 2021-10-21 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0003_alter_house_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('section', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='swipe.house')),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='house',
        ),
        migrations.DeleteModel(
            name='AnnouncementRequest',
        ),
        migrations.AddField(
            model_name='announcement',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='swipe.flat'),
        ),
    ]
