# Generated by Django 3.2.8 on 2021-10-29 16:14

from django.db import migrations, models
import django.db.models.deletion
import swipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0004_auto_20211021_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=swipe.models.get_upload_path)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='swipe.house')),
            ],
        ),
    ]
