# Generated by Django 3.2.8 on 2021-10-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_notification_status'),
        ('swipe', '0005_houseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='users.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='calculation_options',
            field=models.CharField(choices=[('1', 'Наличные'), ('2', 'Безнал'), ('3', 'Ипотека')], max_length=2),
        ),
    ]
