# Generated by Django 3.2.8 on 2021-11-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0006_auto_20211030_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('1', 'Квартиры'), ('2', 'Новострой')], max_length=2),
        ),
    ]
