# Generated by Django 3.2.8 on 2021-11-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0007_alter_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='swipe.announcement'),
        ),
    ]
