# Generated by Django 3.2.8 on 2021-11-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0008_alter_promotion_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='swipe.flat'),
        ),
    ]
