# Generated by Django 3.2.8 on 2021-11-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_notification_status'),
        ('swipe', '0010_auto_20211105_2234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientannouncementfavourites',
            unique_together={('client', 'announcement')},
        ),
        migrations.AlterUniqueTogether(
            name='clienthousefavourites',
            unique_together={('client', 'house')},
        ),
    ]
