# Generated by Django 3.2.8 on 2021-11-06 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0011_auto_20211106_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='square_meter_price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
